### ISSUE TITLE
Follow your steps, but raspberry 3b+ can't start up.

### ISSUE THREAD

**Issue by ZechariahZheng** [ks0n/mfrc522-linux#71]
I have build Image success, but raspberry pi can't start up. Those are my steps:

```shell
sudo cp arch/arm64/boot/Image mnt/fat32/kernel8.img		#copy image to rasp
dtc -O dtb -o bcm2710-rpi-3-b-plus.dtb bcm2710-rpi-3-b-plus_mfrc522_aarch64.dts #dts to dtb
sudo cp bcm2710-rpi-3-b-plus.dtb mnt/fat32/bcm2710-rpi-3-b-plus.dtb #replace old dtb
```

Is anything wrong?

**Comment by Skallwar** [comment]
Maybe the dtb as changed since we did this. Try to convert the dtb of current RaspiOS and replace `spidev@0` device with this:
```dts
			mfrc522@0 {
				compatible = "mfrc522";
				reg = < 0x00 >;
				#address-cells = < 0x01 >;
				#size-cells = < 0x00 >;
				spi-max-frequency = < 0xf4240 >;
				phandle = < 0x68 >;
			};
```

Then recompile to dtb.

If this does not work, I will have a look

**Comment by ZechariahZheng** [comment]
​	According to your suggestion, I have tried to convert the dtb of current RaspiOS to tmp dts, then replace `spidev@0` device in the tmp dts. But it failed to compile to dts. Those are my steps:

```shell
dtc -I dtb -O dts -o a.dts bcm2710-rpi-3-b-plus.dtb  #RaspiOS dtb to dts
vim a.dts   #replace spidev@0
dtc -I dtb -O dtb -o a.dtb a.dts   #compile failed
FATAL ERROR: Blob has incorrect magic number
```

In C module,  I use the dtb generated by [[the Raspberry fork of linux](https://github.com/raspberrypi/linux/)](https://github.com/raspberrypi/linux/), and insmod the  `mfrc522.ko` .It also works, Is anything difference with the changed dtb?

On Rust module, I have built the Image, but it can't start up with the dtb generated by [[the Raspberry fork of linux](https://github.com/raspberrypi/linux/)](https://github.com/raspberrypi/linux/). And in Rust for linux can't find any dtb.

Can you give me some tips? I am a freshman, Thanks very much.

**Comment by Skallwar** [comment]
Sorry for the delay, I will get to it

**Comment by Skallwar** [comment]
> It also works, Is anything difference with the changed dtb?

For us if we did not remove the `spidev@0` and use the dtb for [raspberrypi/linux](https://github.com/raspberrypi/linux/) the module was never probed by the kernel. Do you have `[MFRC522] SPI Probed` in your `dmesg` output?

> ```dtc -I dtb -O dtb -o a.dtb a.dts```

I think this should be `dtc -I dts -O dtb -o a.db a.dts`

Hope this helps

**Comment by ZechariahZheng** [comment]
Thanks for your reply. I have solved it

**Comment by Skallwar** [comment]
So what fixed it? This might help future reader

**Comment by ZechariahZheng** [comment]
The rust_kernel_config in respository is not available. I hava used the config of current RaspiOS, and changed some things.

This is my [kernel_config for aarch64](https://github.com/ZechariahZheng/rpi-linux-module-rust/blob/master/aarch64_defconfig) 
This is my [kernel_config for arm](https://github.com/ZechariahZheng/rpi-linux-module-rust/blob/master/arm_defconfig).

These configs are not concise, but useful.
